version: "3.8"
services:
  app: 
    build: .
    image: flasklet-app:latest
    ports:
      - "8000:8000"
    networks:
      - app-net
    volumes:
      - "./.env:/app/.env"
   
  redis:
    image: redis:latest
    networks:
      - app-net

networks:
  app-net:
